### ISSUE TITLE
Certain extra applications do not install

### ISSUE THREAD

**Issue by Tourniquet88** [WOA-Project/Lumia-Drivers#3] opened 2020-05-31 19:00 UTC
After I redeployed my Cityman Dual Sim and waited till the popup says "its ready", I've noticed that the "Extras" category in Settings is missing, also there is no messging and no woa dailer app installed. 

Airwaves however and USB Function App is however there.

Info: After the popup said "ready to use", I still waited another 20 minutes.

Build 18362

**Comment by gus33000** [comment] 2020-06-12 09:20
Will look into it might be the same issue as cellular

**Comment by gus33000** [comment] 2020-06-12 09:30
Ok so the issue is not really linked to the same issue that plagued cellular. It is however a certificate validity period issue. Apps will not install because your date and time isn't actually set to the correct thing, most likely because you haven't setup wifi on oobe or did something else, so when it tries to install the applications, these fail, I will look into it a bit more to see if there isn't a fix for this possible so I'm not closing this just yet

**Comment by Tourniquet88** [comment] 2020-06-12 12:15
This is correct. I usually don't enable WiFi on OOBE. Isn't Windows using the the date / time of the UEFI compile?

**Comment by gus33000** [comment] 2020-06-12 15:07
Windows uses the OS compile date as a fallback

**Closed** 2020-06-13 14:55 UTC
Labels: P1, bug, confirmed issue, wontfix, works as intended
